general {
  hide_cursor = false
}

background {
  monitor =
  path = $HOME/Pictures/wallpapers/purple-walls.jpg
  # path = screenshot
  blur_passes = 0
  color = rgba(26, 27, 38, 1.0)
}



# TIME (clock)
label {
  monitor =
  text = $TIME
  color = rgba(192, 202, 245, 1.0)
  font_size = 90
  font_family = SF Pro Display
  position = 4, 60           # x = 4% from left
  halign = left
  valign = bottom
}

# DATE (just below clock)
label {
  monitor =
  text = cmd[update:43200000] date +"%A, %d %B %Y"
  color = rgba(192, 202, 245, 1.0)
  font_size = 25
  font_family = SF Pro Display
  position = 4, 30           # x = 4% from left
  halign = left
  valign = bottom
}



input-field {
  monitor = 
  size = 280, 60
  outline_thickness = 0
  border_radius = 10
  blur_passes = 2

  inner_color = rgba(0, 0, 0, 0.0)             # fully transparent background
  font_size = 22
  font_color = rgba(20, 14, 28, 1.0)  
  # font_color = rgba(0, 0, 0, 1.0)    #fully black text
  font_family = JetBrains Mono Nerd Font

  dots_size = 0.3
  dots_spacing = 0.2
  dots_center = true

  fade_on_empty = false
  placeholder_text =  Enter Password
  hide_input = false
  check_color    = rgba(158, 206, 235, 1.0)     # soft blue — success
  # fail_color     = rgba(224, 175, 104, 1.0)   # warm amber — fail (no red at all)
  fail_color = rgba(0, 0, 0, 0.0)               # Fully transparent 
  capslock_color = rgba(169, 177, 214, 1.0)     # muted lavender-gray — capslock
  fail_text = MF,Who the <b>FUCK</b> are you?
  position = 0, 0
  halign = center
  valign = center
}
