wallpaper {
    monitor = LVDS-1
    # path = ~/Pictures/wallpapers/Lock/deep-lock.jpg
    path = ~/Pictures/wallpapers/New/trees eve.jpg
    fit_mode = cover
}

# Optional settings (outside wallpaper blocks)
splash = false
ipc = true
